Repository Samsung/GearVRf, pull requests merged in 2018-03, with the labels that each got.

#1760 ovractivity correct default settings + signalled vulkan fence
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrActivityDelegate.java
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrViewManager.java
  GVRf/Framework/backend_oculus/src/main/jni/ovr_activity.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vulkanInfoWrapper.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vulkanInfoWrapper.h
Labels: will be merged soon

#1759 Fixes camera flickering with Gear controller
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRPicker.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRScene.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRSceneObject.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRViewManager.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRCursorController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRGazeCursorController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRGearCursorController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRInputManager.java
  GVRf/Framework/framework/src/main/jni/view_manager_jni.cpp
Labels: will be merged soon

#1758 X3D parser fixes of ROUTE, MeshCreator changes from maint_v3.x
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/AnimationInteractivityManager.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/X3Dobject.java
Labels: will be merged soon

#1767 [maint_v3.x] framework: set full screen mode from onCreate
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRActivity.java
Labels: will be merged soon

#1773 Bugfixes for vulkan
  GVRf/Framework/framework/src/main/jni/view_manager_jni.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vk_bitmap_image.h
  GVRf/Framework/framework/src/main/jni/vulkan/vk_cubemap_image.h
  GVRf/Framework/framework/src/main/jni/vulkan/vk_framebuffer.h
  GVRf/Framework/framework/src/main/jni/vulkan/vk_imagebase.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vk_imagebase.h
  GVRf/Framework/framework/src/main/jni/vulkan/vk_render_target.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vk_render_target.h
  GVRf/Framework/framework/src/main/jni/vulkan/vk_render_texture_offscreen.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vk_render_texture_offscreen.h
  GVRf/Framework/framework/src/main/jni/vulkan/vk_texture.h
  GVRf/Framework/framework/src/main/jni/vulkan/vulkanCore.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vulkanCore.h
  GVRf/Framework/framework/src/main/jni/vulkan/vulkan_headers.h
  GVRf/Framework/framework/src/main/jni/vulkan/vulkan_image.h
Labels: will be merged soon

#1775 bug fixes for controller
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrViewManager.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRCursorController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRGearCursorController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRInputManager.java
  GVRf/Framework/framework/src/main/jni/objects/components/mesh_collider.cpp
Labels: ready for review

#1783 gradle: updates so we can build with ndk v17
  GVRf/Extensions/gvrf-physics/build.gradle
  GVRf/Framework/backend_daydream/build.gradle
Labels: will be merged soon

#1782 Fixing GVRUnlitVerticalStereoShader and GVRUnlitHorizontalStereoShader
  GVRf/Framework/framework/src/main/jni/engine/renderer/renderer.cpp
  GVRf/Framework/framework/src/main/res/raw/pos_tex_ubo.vsh
  GVRf/Framework/framework/src/main/res/raw/unlit_horizontal_frag.fsh
  GVRf/Framework/framework/src/main/res/raw/unlit_vertical_frag.fsh
Labels: will be merged soon

#1757 Adding special shader for X3D content
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/AnimationInteractivityManager.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/DefinedItem.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/ShaderSettings.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/X3DShader.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/X3Dobject.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/data_types/SFVec2f.java
  GVRf/Extensions/x3d/src/main/res/raw/x3d_surface.fsh
  GVRf/Extensions/x3d/src/main/res/raw/x3d_vertex.vsh
  GVRf/Extensions/x3d/src/main/res/raw/x3d_vertex_template.vsh
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRShader.java
  GVRf/Framework/framework/src/main/jni/gl/gl_uniform_block.cpp
  GVRf/Framework/framework/src/main/jni/objects/data_descriptor.cpp
  GVRf/Framework/framework/src/main/res/raw/fragment_template.fsh
  GVRf/Framework/framework/src/main/res/raw/pointlight.fsh
Labels: will be merged soon

#1769 Bring scene editor back
  GVRf/Framework/framework/src/main/java/org/gearvrf/IViewEvents.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRViewSceneObject.java
  GVRf/tools/gvr-scene-editor/app/build.gradle
  GVRf/tools/gvr-scene-editor/app/src/main/java/org/gearvrf/io/sceneeditor/BaseView.java
  GVRf/tools/gvr-scene-editor/app/src/main/java/org/gearvrf/io/sceneeditor/EditObjectView.java
  GVRf/tools/gvr-scene-editor/app/src/main/java/org/gearvrf/io/sceneeditor/EditableBehavior.java
  GVRf/tools/gvr-scene-editor/app/src/main/java/org/gearvrf/io/sceneeditor/FileBrowserView.java
  GVRf/tools/gvr-scene-editor/app/src/main/java/org/gearvrf/io/sceneeditor/SceneEditorMain.java
  GVRf/tools/gvr-scene-editor/app/src/main/res/layout/edit_object_layout.xml
  GVRf/tools/gvr-scene-editor/build.gradle
  GVRf/tools/gvr-scene-editor/gradle/wrapper/gradle-wrapper.jar
  GVRf/tools/gvr-scene-editor/gradle/wrapper/gradle-wrapper.properties
  GVRf/tools/gvr-scene-editor/settings.gradle
Labels: will be merged soon

#1787 Vulkan: blending and stencil testing
  GVRf/Framework/framework/src/main/jni/engine/renderer/vulkan_renderer.h
  GVRf/Framework/framework/src/main/jni/objects/components/render_data.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vk_imagebase.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vulkanCore.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vulkanCore.h
  GVRf/Framework/framework/src/main/jni/vulkan/vulkanInfoWrapper.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vulkanInfoWrapper.h
  GVRf/Framework/framework/src/main/jni/vulkan/vulkan_flags.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vulkan_flags.h
Labels: will be merged soon

#1788 backend_oculus: ensure the camera rig transform is updated prior to everything else
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrViewManager.java
  GVRf/Framework/backend_oculus/src/main/jni/ovr_activity.cpp
  GVRf/Framework/backend_oculus/src/main/jni/ovr_activity.h
Labels: will be merged soon

#1789 GL: clear stencil buffer correctly
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrViewManager.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRViewManager.java
Labels: will be merged soon

#1799 gazecursor: fixes so events work when docked
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRCursorController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRGazeCursorController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRGearCursorController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRViewSceneObject.java
Labels: will be merged soon

#1801 clang: fix warnings and potential runtime crashes
  GVRf/Framework/framework/src/main/jni/shaders/shader.cpp
  GVRf/Framework/framework/src/main/jni/shaders/shader.h
  GVRf/Framework/framework/src/main/jni/shaders/shader_manager_jni.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vk_bitmap_image.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vk_bitmap_image.h
  GVRf/Framework/framework/src/main/jni/vulkan/vk_imagebase.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vk_imagebase.h
  GVRf/Framework/framework/src/main/jni/vulkan/vk_texture.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vulkanCore.cpp
  GVRf/Framework/framework/src/main/jni/vulkan/vulkan_index_buffer.cpp
Labels: will be merged soon

#1804 Enabled X3D Inline to retrieve remote fbx and x3d files.
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/AnimationInteractivityManager.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/ShaderSettings.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/X3Dobject.java
Labels: will be merged soon

#1806 Remove references to the monoscopic settings in gvr.xml
  GVRf/Framework/backend_monoscopic/src/main/java/org/gearvrf/MonoscopicXMLParser.java
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrMonoscopicViewManager.java
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrXMLParser.java
  GVRf/Framework/framework/src/main/assets/_gvr.xml
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRActivity.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/utility/VrAppSettings.java
Labels: will be merged soon

#1794 build: support switching to clang
  GVRf/Extensions/gvrf-physics/build.gradle
  GVRf/Framework/backend_daydream/build.gradle
  GVRf/Framework/backend_monoscopic/build.gradle
  GVRf/Framework/backend_monoscopic/src/main/clang/Android.mk
  GVRf/Framework/backend_monoscopic/src/main/clang/Application.mk
  GVRf/Framework/backend_monoscopic/src/main/jni/Application.mk
  GVRf/Framework/backend_oculus/build.gradle
  GVRf/Framework/backend_oculus/src/main/clang/Android.mk
  GVRf/Framework/backend_oculus/src/main/clang/Application.mk
  GVRf/Framework/backend_oculus/src/main/jni/Application.mk
  GVRf/Framework/framework/build.gradle
  GVRf/Framework/framework/src/main/clang/Android.mk
  GVRf/Framework/framework/src/main/clang/Application.mk
  GVRf/Framework/framework/src/main/jni/Application.mk
Labels: will be merged soon

#1812 framework: tweaks so it compiles with the lightbuffer pr
  GVRf/Framework/framework/src/main/jni/engine/renderer/renderer.cpp
  GVRf/Framework/framework/src/main/jni/engine/renderer/vulkan_renderer.cpp
  GVRf/Framework/framework/src/main/jni/objects/components/render_data.cpp
  GVRf/Framework/framework/src/main/jni/objects/lightlist.cpp
  GVRf/Framework/framework/src/main/jni/objects/lightlist.h
  GVRf/Framework/framework/src/main/jni/objects/scene.h
  GVRf/Framework/framework/src/main/jni/objects/scene_jni.cpp
Labels: needs work

#1808 logger: add egl checking macros
  GVRf/Framework/backend_daydream/src/main/jni/CMakeLists.txt
  GVRf/Framework/framework/src/main/jni/util/gvr_log.h
Labels: will be merged soon
