Repository Samsung/GearVRf, pull requests merged in 2018-07, with the labels that each got.

#1915 add support for angular velocity and acceleration
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVREventListeners.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/IActivityEvents.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRGearCursorController.java
Labels: will be merged soon

#1925 framework, video scene object: don't automatically restart playing on resume
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRVideoSceneObject.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRVideoSceneObjectPlayer.java
Labels: will be merged soon

#1917 Adding support in renderer for blend shapes
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRFloatImage.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRMeshMorph.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/GVRAnimation.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/GVRMorphAnimation.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/keyframe/GVRAnimationController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/keyframe/GVRFloatAnimation.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/keyframe/GVRMorphController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/shaders/GVRPhongShader.java
  GVRf/Framework/framework/src/main/jni/engine/renderer/gl_renderer.cpp
  GVRf/Framework/framework/src/main/jni/gl/gl_bitmap_image.cpp
  GVRf/Framework/framework/src/main/jni/gl/gl_float_image.h
  GVRf/Framework/framework/src/main/jni/objects/bounding_volume.cpp
  GVRf/Framework/framework/src/main/jni/objects/textures/float_image.cpp
  GVRf/Framework/framework/src/main/jni/objects/textures/float_image.h
  GVRf/Framework/framework/src/main/jni/objects/textures/float_image_jni.cpp
  GVRf/Framework/framework/src/main/res/raw/fragment_template.fsh
  GVRf/Framework/framework/src/main/res/raw/fragment_template_multitex.fsh
  GVRf/Framework/framework/src/main/res/raw/phong_surface.fsh
  GVRf/Framework/framework/src/main/res/raw/phong_surface_layertex.fsh
  GVRf/Framework/framework/src/main/res/raw/phong_surface_multitex.fsh
  GVRf/Framework/framework/src/main/res/raw/pos_norm_multitex.vsh
  GVRf/Framework/framework/src/main/res/raw/vertex_template.vsh
  GVRf/Framework/framework/src/main/res/raw/vertex_template_multitex.vsh
  GVRf/Framework/framework/src/main/res/raw/vertexmorph.vsh
Labels: will be merged soon

#1929 Fixing two post effect
  GVRf/Framework/framework/src/main/jni/view_manager_jni.cpp
Labels: will be merged soon

#1932 gradle: include the support for vulkan validation layers only in the debug builds
  GVRf/Framework/framework/build.gradle
Labels: will be merged soon

#1918 Improvements to rag doll demo
  GVRf/Extensions/gvrf-physics/build.gradle
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRConeTwistConstraint.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRConstraint.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRFixedConstraint.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRGenericConstraint.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRHingeConstraint.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRPhysicsLoader.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRPoint2PointConstraint.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRRigidBody.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRSliderConstraint.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/GVRWorld.java
  GVRf/Extensions/gvrf-physics/src/main/java/org/gearvrf/physics/PhysicsDragger.java
  GVRf/Extensions/gvrf-physics/src/main/jni/engine/bullet/bullet_rigidbody.cpp
  GVRf/Extensions/gvrf-physics/src/main/jni/engine/bullet/bullet_world.cpp
  GVRf/Extensions/gvrf-physics/src/main/jni/engine/bullet/bullet_world.h
  GVRf/Extensions/gvrf-physics/src/main/jni/engine/physics_rigidbody_jni.cpp
  GVRf/Extensions/gvrf-physics/src/main/jni/engine/physics_world.h
  GVRf/Extensions/gvrf-physics/src/main/jni/engine/physics_world_jni.cpp
Labels: will be merged soon

#1935 Fix for view's anti-aliasing issue
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRViewSceneObject.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/shaders/GVROESConvolutionShader.java
  GVRf/Framework/framework/src/main/res/raw/oes_convolution_frag.fsh
  GVRf/Framework/framework/src/main/res/raw/oes_convolution_vert.vsh
Labels: will be merged soon

#1930 Add GVRApplication allowing making apps not derived from GVRActivity
  GVRf/Extensions/3DCursor/3DCursorLibrary/src/main/java/org/gearvrf/io/cursor3d/settings/BaseView.java
  GVRf/Extensions/3DCursor/3DCursorLibrary/src/main/java/org/gearvrf/io/cursor3d/settings/CursorConfigView.java
  GVRf/Extensions/3DCursor/3DCursorLibrary/src/main/java/org/gearvrf/io/cursor3d/settings/SettingsView.java
  GVRf/Extensions/MixedReality/src/main/java/org/gearvrf/mixedreality/GVRMixedReality.java
  GVRf/Extensions/ResonanceAudio/resonanceaudio/src/main/java/org/gearvrf/resonanceaudio/GVRAudioManager.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/AnchorImplementation.java
  GVRf/Framework/backend_daydream/src/main/java/org/gearvrf/DayDreamControllerReader.java
  GVRf/Framework/backend_daydream/src/main/java/org/gearvrf/DaydreamActivityDelegate.java
  GVRf/Framework/backend_daydream/src/main/java/org/gearvrf/DaydreamViewManager.java
  GVRf/Framework/backend_daydream/src/main/jni/daydream_renderer_jni.cpp
  GVRf/Framework/backend_monoscopic/src/main/java/org/gearvrf/MonoscopicActivityDelegate.java
  GVRf/Framework/backend_monoscopic/src/main/java/org/gearvrf/MonoscopicConfigurationManager.java
  GVRf/Framework/backend_monoscopic/src/main/java/org/gearvrf/MonoscopicRotationSensor.java
  GVRf/Framework/backend_monoscopic/src/main/java/org/gearvrf/MonoscopicViewManager.java
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrActivityDelegate.java
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrActivityNative.java
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrConfigurationManager.java
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrViewManager.java
  GVRf/Framework/backend_oculus/src/main/java/org/gearvrf/OvrVrapiActivityHandler.java
  GVRf/Framework/backend_oculus/src/main/jni/ovr_activity.cpp
  GVRf/Framework/backend_oculus/src/main/jni/ovr_activity.h
  GVRf/Framework/backend_oculus/src/main/jni/ovr_activity_jni.cpp
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRActivity.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRApplication.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRCameraRig.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRConfigurationManager.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRContext.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRContextProxy.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRRenderBundle.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRRenderData.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRRenderTarget.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRScene.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRShaderTemplate.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRViewManager.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRAndroidWearTouchpad.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRCursorController.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/IWearTouchpadEvents.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRCameraSceneObject.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRKeyboardSceneObject.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRTextViewSceneObject.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRVideoSceneObject.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRViewSceneObject.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/view/GVRFrameLayout.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/view/GVRTextView.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/view/GVRWebView.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/script/GVRScriptManager.java
Labels: ready for review

#1941 Fix shader compilation error on Mali
  GVRf/Framework/framework/src/main/java/org/gearvrf/shaders/GVRPBRShader.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/shaders/GVRTextureShader.java
Labels: ready for review

#1882 fix normal mapping
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/X3DLoader.java
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/X3DShader.java
  GVRf/Extensions/x3d/src/main/res/raw/x3d_surface.fsh
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRJassimpAdapter.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/shaders/GVRPhongLayeredShader.java
  GVRf/Framework/framework/src/main/jni/vulkan/vulkan_shader.cpp
  GVRf/Framework/framework/src/main/res/raw/color_blend_frag.fsh
  GVRf/Framework/framework/src/main/res/raw/cubemap_frag.fsh
  GVRf/Framework/framework/src/main/res/raw/cubemap_reflection_frag.fsh
  GVRf/Framework/framework/src/main/res/raw/fragment_template.fsh
  GVRf/Framework/framework/src/main/res/raw/inverted_colors_fragment.fsh
  GVRf/Framework/framework/src/main/res/raw/normalmap.vsh
  GVRf/Framework/framework/src/main/res/raw/pbr_surface.fsh
  GVRf/Framework/framework/src/main/res/raw/phong_surface.fsh
  GVRf/Framework/framework/src/main/res/raw/phong_surface_layertex.fsh
  GVRf/Framework/framework/src/main/res/raw/phong_surface_multitex.fsh
  GVRf/Framework/framework/src/main/res/raw/pos_norm_multitex.vsh
  GVRf/Framework/framework/src/main/res/raw/pos_norm_tex.vsh
  GVRf/Framework/framework/src/main/res/raw/texture_surface.fsh
  GVRf/Framework/framework/src/main/res/raw/unlit_horizontal_frag.fsh
  GVRf/Framework/framework/src/main/res/raw/unlit_tex_frag.fsh
  GVRf/Framework/framework/src/main/res/raw/unlit_vertical_frag.fsh
  GVRf/Framework/framework/src/main/res/raw/vertex_template.vsh
  GVRf/Framework/framework/src/main/res/raw/vertex_template_multitex.vsh
Labels: will be merged soon

#1934 video-scene-object: remove the activity events listener whenever appropriate
  GVRf/Framework/framework/src/main/java/org/gearvrf/scene_objects/GVRVideoSceneObject.java
Labels: will be merged soon

#1936 X3D: Fixed errors with mesh having normals; new cursor setting.
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/X3Dobject.java
Labels: will be merged soon

#1937 backend_oculus: disable head tracking updates for a frozen camera rig
  GVRf/Framework/backend_oculus/src/main/jni/ovr_activity.cpp
Labels: will be merged soon

#1943 x3d: remove duplicate material_unforms from the shader
  GVRf/Extensions/x3d/src/main/java/org/gearvrf/x3d/X3DShader.java
Labels: will be merged soon

#1948 Fix receiving of IActivityEvents.onControllerEvent
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRGearCursorController.java
Labels: will be merged soon

#1953 Eliminate the special case scene root on the C++ side
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRScene.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRSceneObject.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRViewManager.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRCursorController.java
  GVRf/Framework/framework/src/main/jni/objects/scene.cpp
  GVRf/Framework/framework/src/main/jni/objects/scene.h
  GVRf/Framework/framework/src/main/jni/objects/scene_jni.cpp
  GVRf/Framework/framework/src/main/jni/objects/scene_object.cpp
Labels: ready for review

#1954 Dirty flag of lights not cleared at all
  GVRf/Framework/framework/src/main/jni/objects/lightlist.cpp
Labels: ready for review

#1946 Optimize animation data structures
  GVRf/Framework/framework/src/main/java/org/gearvrf/GVRJassimpAdapter.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/GVRMorphAnimation.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/keyframe/GVRAnimationChannel.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/keyframe/GVRFloatAnimation.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/keyframe/GVRKeyFrameAnimation.java
  GVRf/Framework/framework/src/main/java/org/gearvrf/animation/keyframe/GVRQuatAnimation.java
Labels: needs work
